feat(elm): add panel for creating questions
forcecraft/aion pull request #45
Opened 2017-07-08 12:28 UTC by pmrukot

**Summary**

This PR introduces a new view called "Panel". At first, it will support adding questions to existing categories.

<img width="492" alt="screen shot 2017-07-08 at 14 27 53" src="https://user-images.githubusercontent.com/13131966/27985358-b1a8c7a2-63e9-11e7-93aa-667508549371.png">

TODO:
- [x] Create submit form in elm
- [ ] Integrate with backend

**Related issues**
https://github.com/pmrukot/aion/issues/42

2017-07-08 13:39 UTC, mrapacz commented
Looks good so far, good luck on the way!

2017-07-16 20:30 UTC, mrapacz requested changes
Maybe we should think about some form or precaution against submitting the same form a couple of times? We could either not digest the same request twice or display a notification after submitting the first correct request from Elm. Anyway, what happens now if the input cannot be inserted into db? The error msgs are only local, the user won't see them. 

Apart from that, the code looks pretty neat, tell me what you think on the precautions (we can add it in another PR possibly?) and fix the smaller things I marked and I think we can safely pull it :+1: :100: 

One last side note, a simple UX thing - 
![image](https://user-images.githubusercontent.com/15965147/28251098-4ba0ca98-6a76-11e7-851a-90c05b8c74cb.png)
Maybe we should get rid of the quotation marks here?

2017-07-16 20:30 UTC, mrapacz commented on aion/web/elm/src/Panel/View.elm
> +            , input [ placeholder "Kot,kocur,kotek", onInput SetNewAnswerContent ] []
I wouldn't mix up Polish with English here, maybe change these to whatever in English, just so we stay cohesive

2017-07-16 20:30 UTC, mrapacz commented on aion/web/elm/src/Update.elm
> +                { model | panelData = newPanelData } ! []
Actually these can be rewritten in a simpler manner:
```        SetNewAnswerContent answerContent ->
            let
                oldPanelData =
                    model.panelData
            in
                { model | panelData = { oldPanelData | newAnswerContent = answerContent } } ! []```

2017-07-17 18:38 UTC, jtkpiotr commented on aion/web/models/question.ex
> +      struct
Maybe we can create separate methods for creating changeset for params that contains and does not contain subject.

2017-07-17 19:58 UTC, pmrukot commented on aion/web/models/question.ex
> +      struct
I refactored it to be similar to answer's changeset and changed controller a little to better handle different cases.

2017-07-17 20:25 UTC, pmrukot commented
@mrapacz
About quotation marks: currently we are using `elm-select` which uses types as select options. I am giving him list of strings though, not type. And there is currently no support in Elm for function like haskell's well known [`read`](http://zvon.org/other/haskell/Outputprelude/read_f.html). No sure how can we handle it.

I think that we should merge it and reiterate to make it user friendly. Purpose of this PR was to make end-to-end Question+Answer creation, with simple form. Let's assume happy path since we are in early stage of development and add improvements for user experience in next PR. I can open an issue but I suggest following improvements:
- [ ] Notifications if the request was successful or not
- [ ] Form validation
- [ ] Clearing the form after successful submit
- [ ] Possibility to add more than one possible answer
Any more?

2017-07-17 20:48 UTC, mrapacz commented on aion/web/elm/src/Panel/View.elm
> +            , input [ placeholder "How much is 2+2?", onInput SetNewQuestionContent ] []
👍 💯 🥇

2017-07-17 20:53 UTC, mrapacz commented
Okay, we can do it in other PRs, although if we want functionality first, then we should start with adding multiple answers first, then move to UX and similar

2017-07-17 21:35 UTC, mrapacz commented
![retrokid](https://user-images.githubusercontent.com/15965147/28290910-9aa311e6-6b48-11e7-8951-4c2e35a721cf.gif)

2017-07-17 21:36 UTC, mrapacz approved these changes

2017-07-18 20:06 UTC, jtkpiotr approved these changes

2017-07-19 17:28 UTC, merged